### ISSUE TITLE
Cant validate

### ISSUE THREAD

**Issue by Onyx808** [WowzaMediaSystems/wse-plugin-referervalidate#2]
Hello,

I follow as best I could this instructions https://www.wowza.com/docs/how-to-control-access-to-your-application-by-checking-referer-domain-modulereferervalidate

But for whatever reason I keep getting the "You do not have premission to access this content"

I have uploaded the image.gif file to the application folder where the .stream file is at and added the image tag at the top of the html.

Any idea what can it be?

**Comment by wowza-mbrinker** [comment]
It's best if you can [open a support ticket](https://www.wowza.com/support/open-ticket) with us so that we can review your configuration. Please send a zip of your Wowza server's conf/, logs/, transcoder/, and HTML page that has your image tag and player code.
