### ISSUE TITLE
Prevent downloading video

### ISSUE THREAD

**Issue by tuanth89** [WowzaMediaSystems/wse-plugin-referervalidate#3]
Firstly, thanks for this plugin !
Use this plugin can be prevent user download video ?

**Comment by Wowza-Rose** [comment]
Yes, this is one of the tools that can be used to prevent a user from downloading a VOD file. This can be combated in a few other ways as well.

- SSL on the site with the player on.
- Secure Token- this can help as well.
- Validate 'where' the request was made from - so referer validate module - downloaders generally do not have a referer so it fail - but players pass one on.
- DRM works too - but more complex to implement.
